AWSTemplateFormatVersion: 2010-09-09
Description: >-
  wunderlink

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  Domain:
    Type: String
    Description: domain name
  CertificateArn:
    Type: String
    Description: ssl certficate arn for domain
  Route53ZoneId:
    Type: String
    Description: zoneid in route 53

Resources:
  LinksTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2


  LinksHttpApi:
   Type: AWS::Serverless::HttpApi
   Properties:
     CorsConfiguration: True
     Domain:
        CertificateArn: !Ref CertificateArn
        DomainName: !Ref Domain
        Route53:
          HostedZoneId: !Ref Route53ZoneId
        
  getAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-all-items.getAllItemsHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get all items from a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LinksTable
      Environment:
        Variables:
          LINKS_TABLE: !Ref LinksTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /
            ApiId: !Ref LinksHttpApi
            Method: GET

  getByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-by-id.getByIdHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get one item by id from a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LinksTable
      Environment:
        Variables:          
          LINKS_TABLE: !Ref LinksTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{id}
            ApiId: !Ref LinksHttpApi
            Method: GET

  delByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/del-by-id.deleteByIdHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: deletes links from link table
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LinksTable
      Environment:
        Variables:
          LINKS_TABLE: !Ref LinksTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref LinksHttpApi
            Path: /d/{id}
            Method: GET
  
  putItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/put-item.putItemHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LinksTable
      Environment:
        Variables:
          LINKS_TABLE: !Ref LinksTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref LinksHttpApi
            Path: /
            Method: POST




